services:
  db:
    image: mysql/mysql-server:latest
    container_name: wpd-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'WPD'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '12345678'
      MYSQL_ROOT_PASSWORD: root # กำหนด user ของ root mysql
    volumes:
      - 'mysql:/var/lib/mysql'
    networks:
      - wpd-network
    ports:
      - '3306:3306'
    healthcheck:
      test:
        ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-uuser', '-p12345678']
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    image: apichayauwu/wpd-backend:latest
    container_name: wpd-backend
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: development
      PORT: 8000
      # MySQL
      MYSQL_ROOT_HOST: '%'
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345678
      MYSQL_DATABASE: WPD
      LINE_CLIENT_ID: 2007135016
      INTERNAL_ID_SECRET: uiiriuiiir
    networks:
      - wpd-network
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  frontend:
    image: apichayauwu/wpd-liff:latest
    container_name: wpd-liff
    environment:
      VITE_LIFF_ID: 2007135016-8GpyXVpN
      VITE_LIFF_ID_2: 2007135016-OrLBVXLa
      BASE_URL: http://localhost:5173
      API_URL: http://backend:8000
    ports:
      - '5173:5173'
    depends_on:
      - backend
    networks:
      - wpd-network
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
networks:
  wpd-network:
    driver: bridge

volumes:
  mysql:
    driver: local
