services:
  redis:
    image: redis:7-alpine
    container_name: redis-server
    restart: unless-stopped

    # Redis configuration with security
    command: >
      redis-server 
      --requirepass ${REDIS_PASSWORD}
      --bind 0.0.0.0
      --maxmemory 256mb
      --maxmemory-policy noeviction
      --appendonly yes
      --appendfsync everysec
      --rename-command FLUSHDB ""
      --rename-command FLUSHALL ""
      --rename-command DEBUG ""
      --rename-command CONFIG ""

    ports:
      - '6379:6379'

    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro

    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

    # Health check
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 30s

    # Logging configuration
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

networks:
  wpd-network:
    driver: bridge

volumes:
  redis_data:
    driver: local
