name: CI
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set image tag
        id: vars
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "tag=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=commit-${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
          fi
      
      - name: Run build script
        env:
          IMAGE_TAG: ${{ steps.vars.outputs.tag }}
        run: |
          chmod +x ./build.sh
          ./build.sh "$IMAGE_TAG"
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Pull image from Docker Hub and push to ECR
        env:
          ECR_REGISTRY: 450428376374.dkr.ecr.ap-southeast-2.amazonaws.com
          ECR_REPOSITORY: wanpordee/backend
          DOCKERHUB_IMAGE: apichayauwu/wpd-backend
          IMAGE_TAG: ${{ steps.vars.outputs.tag }}
        run: |
          # Pull from Docker Hub
          docker pull $DOCKERHUB_IMAGE:$IMAGE_TAG
          
          # Tag for ECR
          docker tag $DOCKERHUB_IMAGE:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag $DOCKERHUB_IMAGE:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          
          # Push to ECR
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
